- array 생성
- array 표시
- array 병합

# Array 생성

In [1]:
from numpy import array

In [2]:
# create array
l = [1.0, 2.0, 3.0]
a = array(l)

In [5]:
# create empyt array
from numpy import empty
a = empty([3,3])
print(a)

[[5.08851955e+074 1.70704615e-312 5.88427735e-307]
 [6.37344683e-322 6.95334336e-310 6.95334340e-310]
 [1.79209176e-313 2.00886795e-308 6.21822213e+175]]


In [6]:
# create zero array
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
# create one array
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


# Array 표시

In [10]:
# display array
print(a)

[1. 1. 1. 1. 1.]


In [11]:
# display array shape
print(a.shape)

(5,)


In [12]:
# display array data type
print(a.dtype)

float64


# Array 병합 (Combining Arrays)

In [16]:
# creat array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([1,2,3])
print("a1 :\n", a1)
# create second array
a2 = array([4,5,6])
print("a2 :\n", a2)
# create vertical stack
a3 = vstack((a1, a2))
print("vertical stack :\n", a3)
print(a3.shape)

a1 :
 [1 2 3]
a2 :
 [4 5 6]
vertical stack :
 [[1 2 3]
 [4 5 6]]
(2, 3)


In [17]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print("a1 :\n", a1)
# create second array
a2 = array([4,5,6])
print("a2 :\n", a2)
# create horizontal stack
a3 = hstack((a1, a2))
print("horizontal stack :\n", a3)
print(a3.shape)

a1 :
 [1 2 3]
a2 :
 [4 5 6]
horizontal stack :
 [1 2 3 4 5 6]
(6,)


In [35]:
import numpy as np
x = np.arange(4)
print(x)
# Transposing a 1-D array returns an unchanged view of the original array
print(np.transpose(x))
x = x.reshape((2,2))
print(x)
print(np.transpose(x))

[0 1 2 3]
[0 1 2 3]
[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


# Array Indexing

In [36]:
# negative array indexing
# define array
data = np.array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])

55
11


In [37]:
# index two-dimensional array
data = np.array([
    [11, 22],
    [33, 44],
    [55, 66]
])
# index data
print(data[0,0])

11


In [38]:
# index  row of two-dimesional array
data = np.array([
    [11, 22],
    [33, 44],
    [55, 66]
])
# index data
print(data[0,])

[11 22]


# Array Slicing
data[from:to]

In [39]:
# slice a one-dimensional array
data = np.array([11, 22, 33, 44, 55])
print(data[1:])

[22 33 44 55]


In [40]:
# slice a subset of a one-dimensional array
print(data[0:1])

[11]


In [41]:
# negative slicing of a one-dimensional array
print(data[-2:])

[44 55]


In [42]:
# two dimensional slicing
data = array([
    [11, 22 ,33],
    [44, 55, 66],
    [77, 88, 99]
])

print(data[:, -1])
print(data[:, 1:])

[33 66 99]
[[22 33]
 [55 66]
 [88 99]]


In [43]:
split = 2
train, test = data[:split, :], data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


# Array Reshaping

In [44]:
data = [
    [11, 22],
    [33, 44],
    [55, 66]
]
data = np.array(data)
print(data.shape)

(3, 2)


In [45]:
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


## Reshape 1D to 2D Array


In [55]:
data = np.array([11, 22, 33, 44, 55, 66])
print(data)

# reshape
data = data.reshape(3, 2)
print(data)

[11 22 33 44 55 66]
[[11 22]
 [33 44]
 [55 66]]


## Reshape 2D to 3D Array

In [51]:
print(data)
print(data.reshape(3, 2, 1))

[[11 22]
 [33 44]
 [55 66]]
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]


# Array Broadcasting

In [56]:
# broadcast scalar to one-dimensional array
a = np.array([1, 2, 3])
b = 2
c = a + b
print(c)

[3 4 5]


In [59]:
# broadcast one-dimensional array to two-dimensional array
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = np.array([1, 2, 3])
c = a + b
print(c)

[[2 4 6]
 [5 7 9]]


In [64]:
z = np.maximum(c, 6)
print(z)

[[6 6 6]
 [6 7 9]]


# Vector

# create a vector
v = np.array([1, 2, 3])
print(v)

In [66]:
# vector division
a = array([1, 2, 3])
b = array([1, 2, 3])
c = a/b
print(c)

[1. 1. 1.]
