- array 생성
- array 표시
- array 병합
- vector

# Array 생성

In [1]:
from numpy import array

In [2]:
# create array
l = [1.0, 2.0, 3.0]
a = array(l)

In [5]:
# create empyt array
from numpy import empty
a = empty([3,3])
print(a)

[[5.08851955e+074 1.70704615e-312 5.88427735e-307]
 [6.37344683e-322 6.95334336e-310 6.95334340e-310]
 [1.79209176e-313 2.00886795e-308 6.21822213e+175]]


In [6]:
# create zero array
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
# create one array
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


# Array 표시

In [10]:
# display array
print(a)

[1. 1. 1. 1. 1.]


In [11]:
# display array shape
print(a.shape)

(5,)


In [12]:
# display array data type
print(a.dtype)

float64


# Array 병합 (Combining Arrays)

In [16]:
# creat array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([1,2,3])
print("a1 :\n", a1)
# create second array
a2 = array([4,5,6])
print("a2 :\n", a2)
# create vertical stack
a3 = vstack((a1, a2))
print("vertical stack :\n", a3)
print(a3.shape)

a1 :
 [1 2 3]
a2 :
 [4 5 6]
vertical stack :
 [[1 2 3]
 [4 5 6]]
(2, 3)


In [17]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print("a1 :\n", a1)
# create second array
a2 = array([4,5,6])
print("a2 :\n", a2)
# create horizontal stack
a3 = hstack((a1, a2))
print("horizontal stack :\n", a3)
print(a3.shape)

a1 :
 [1 2 3]
a2 :
 [4 5 6]
horizontal stack :
 [1 2 3 4 5 6]
(6,)


In [35]:
import numpy as np
x = np.arange(4)
print(x)
# Transposing a 1-D array returns an unchanged view of the original array
print(np.transpose(x))
x = x.reshape((2,2))
print(x)
print(np.transpose(x))

[0 1 2 3]
[0 1 2 3]
[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


# Array Indexing

In [36]:
# negative array indexing
# define array
data = np.array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])

55
11


In [37]:
# index two-dimensional array
data = np.array([
    [11, 22],
    [33, 44],
    [55, 66]
])
# index data
print(data[0,0])

11


In [38]:
# index  row of two-dimesional array
data = np.array([
    [11, 22],
    [33, 44],
    [55, 66]
])
# index data
print(data[0,])

[11 22]


# Array Slicing
data[from:to]

In [39]:
# slice a one-dimensional array
data = np.array([11, 22, 33, 44, 55])
print(data[1:])

[22 33 44 55]


In [40]:
# slice a subset of a one-dimensional array
print(data[0:1])

[11]


In [41]:
# negative slicing of a one-dimensional array
print(data[-2:])

[44 55]


In [42]:
# two dimensional slicing
data = array([
    [11, 22 ,33],
    [44, 55, 66],
    [77, 88, 99]
])

print(data[:, -1])
print(data[:, 1:])

[33 66 99]
[[22 33]
 [55 66]
 [88 99]]


In [43]:
split = 2
train, test = data[:split, :], data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


# Array Reshaping

In [44]:
data = [
    [11, 22],
    [33, 44],
    [55, 66]
]
data = np.array(data)
print(data.shape)

(3, 2)


In [45]:
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


## Reshape 1D to 2D Array


In [55]:
data = np.array([11, 22, 33, 44, 55, 66])
print(data)

# reshape
data = data.reshape(3, 2)
print(data)

[11 22 33 44 55 66]
[[11 22]
 [33 44]
 [55 66]]


## Reshape 2D to 3D Array

In [51]:
print(data)
print(data.reshape(3, 2, 1))

[[11 22]
 [33 44]
 [55 66]]
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]


# Array Broadcasting

In [56]:
# broadcast scalar to one-dimensional array
a = np.array([1, 2, 3])
b = 2
c = a + b
print(c)

[3 4 5]


In [59]:
# broadcast one-dimensional array to two-dimensional array
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = np.array([1, 2, 3])
c = a + b
print(c)

[[2 4 6]
 [5 7 9]]


In [64]:
z = np.maximum(c, 6)
print(z)

[[6 6 6]
 [6 7 9]]


# Vector

# create a vector
v = np.array([1, 2, 3])
print(v)

In [66]:
# vector division
a = array([1, 2, 3])
b = array([1, 2, 3])
c = a/b
print(c)

[1. 1. 1.]


## Vector dot product

In [2]:
import numpy as np
# vector dot product
a = np.array([1, 2, 3])

b = np.array([1, 2, 3])

c = a.dot(b)
print(c)

14


In [4]:
# triangular matrices
import numpy as np

# define square matrix
M = np.array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]
])

print(M)

# lower triangular matrix
lower = np.tril(M)
print(lower)
# upper triangular matrix
upper = np.triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [6]:
# matrix trace
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A)
# cacluate trace
B = np.trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [8]:
# matrix determinant

import numpy as np
# define matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A)

# calculate determinant
B = np.linalg.det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735392994e-16


In [11]:
# vector rank
# rank
v1 = np.array([1,2,3])
print(v1)
vr1 = np.linalg.matrix_rank(v1)
print(vr1)
# zero rank
v2 = np.array([0,0,0,0,0])
print(v2)
vr2 = np.linalg.matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


In [13]:
# matrix rank
# rank0
M0 = np.array([
    [0,0],
    [0,0]
])
print(M0)
mr0 = np.linalg.matrix_rank(M0)
print(mr0)

# rank1
M1 = np.array([
    [1, 2],
    [1, 2]
])
print(M1)
mr1 = np.linalg.matrix_rank(M1)
print(mr1)

# rank2
M2 = np.array([
    [1, 2],
    [3, 14]
])
print(M2)
mr2 = np.linalg.matrix_rank(M2)
print(mr2)

[[0 0]
 [0 0]]
0
[[1 2]
 [1 2]]
1
[[ 1  2]
 [ 3 14]]
2


### Sparse Matrices

In [16]:
# sparse matrix
import numpy as np
from scipy.sparse import csr_matrix
# create dense matrix
A = np.array([
  [1, 0, 0, 1, 0, 0],
  [0, 0, 2, 0, 0, 1],
  [0, 0, 0, 2, 0, 0]    
])
print(A)
# convert to sparse matrix (CSR method)
S = csr_matrix(A)
# S tells us where the non-zero value is located
print(S)
# recontruct dense matrix
B = S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [17]:
# sparsity calculation
import numpy as np
# create dense matrix
A = np.array([
  [1, 0, 0, 1, 0, 0],
  [0, 0, 2, 0, 0, 1],
  [0, 0, 0, 2, 0, 0]    
])
print(A)
# calculate sparsity
sparsity = 1.0 - np.count_nonzero(A) / A.size
print(sparsity)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
0.7222222222222222


## Tensors

In [19]:
# tensor addition
from numpy import array
# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# add tensors
C = A + B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


In [20]:
# tensor subtraction
from numpy import array
# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# add tensors
C = A - B
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


Hadamard product operation between tensors

In [22]:
# tensor Hadamard product
import numpy as np
# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# multiply tensors
C=A*B
print(C)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


In [23]:
# tensor division
from numpy import array
# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# divide tensors
C=A/B
print(C)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [25]:
# tensor product
# define first vector
A = np.array([1,2])
# define second vector
B = np.array([3, 4])
# calculate tensor product
C = np.tensordot(A, B, axes=0)
print(C)

# It is different multiplying, it does not respect the number of dimensions
D = A * B
print(D)

# Notice that depending on how we make the product of one or the other the position changes
F = np.tensordot(B, A, axes=0)
print(F)

[[3 4]
 [6 8]]
[3 8]
[[3 6]
 [4 8]]


# LU Decomposition

In [26]:
# LU decomposition
import numpy as np
from scipy.linalg import lu

# define a square matric
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(A)

# factorize
P, L, U = lu(A)
print(P)
print(L)
print(U)

# reconstruct
B = P.dot(L).dot(U)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# QR Decomposition

In [36]:
# QR decomposition
import numpy as np
from scipy.linalg import qr

# define rectangular matrix
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A)
# factorize
Q, R = qr(A, mode='qr')
print(Q)
print(R)

# reconstruct
B = Q.dot(R)
print(B)


[[1 2]
 [3 4]
 [5 6]]
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


# Cholesky decomposition

In [39]:
# Cholesky decomposition
import numpy as np
from numpy.linalg import cholesky
# define symetric matrix
A = np.array([
    [2, 1, 1],
    [1, 2, 1],
    [1, 1, 2]
])
print(A)
# factorize
L = cholesky(A)
print(L)
# reconstruct
B = L.dot(L.T.conj())
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


# Eigen decomposition

In [47]:
# eigen decomposition
import numpy as np
from numpy.linalg import eig
# define matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(A)
# factorize
values, vectors = eig(A)
print(values)
print(vectors)
# dot(Array, normalized eigenvectors) = eignevalues * normalized eigenvectors
print(A.dot(vectors))
print(values*vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
[[-3.73863537e+00  8.77649763e-01 -3.88578059e-16]
 [-8.46653421e+00  9.68877101e-02 -3.33066907e-16]
 [-1.31944331e+01 -6.83874343e-01 -7.21644966e-16]]
[[-3.73863537e+00  8.77649763e-01 -3.98417052e-16]
 [-8.46653421e+00  9.68877101e-02  7.96834105e-16]
 [-1.31944331e+01 -6.83874343e-01 -3.98417052e-16]]


In [50]:
# confirm eigenvector
import numpy as np
from numpy.linalg import eig
# define marix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# factorize
values, vectors = eig(A)

# confirm first eigenvector
B = A.dot(vectors[:,0])
print(B)
C= vectors[:,0] * values[0]
print(C)


[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


In [52]:
# reconstruct matrix
import numpy as np
from numpy.linalg import inv, eig

# define matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(A)
# factorize
values, vectors = eig(A)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = np.diag(values)
# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# SDV

In [53]:
# singular-value decomposition
import numpy as np
from scipy.linalg import svd
# define matrix
A = array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A)
# factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [55]:
# reconstruct rectangluar matrix from svd
import numpy as np
from scipy.linalg import svd
# define matrix
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A)
# factorize
U, s, V = svd(A)
# create m x n Sigma matrix
Sigma = np.zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = np.diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [56]:
# reconstruct square matrix from svd
from numpy import array
from numpy import diag
from scipy.linalg import svd
# define matrix
A = array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])
print(A)
# factorize
U, s, V = svd(A)

# create n x n Sigma matrix
Sigma = diag(s)

# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# pseudoinverse

In [57]:
# pseudoinverse
from numpy import array
from numpy.linalg import pinv
# define matrix
A = array([
  [0.1, 0.2],
  [0.3, 0.4],
  [0.5, 0.6],
  [0.7, 0.8]])
print(A)
# calculate pseudoinverse
B = pinv(A)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


# Dimesionality Reduction

In [58]:
# data reduction with svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define matrix
A = array([
  [1,2,3,4,5,6,7,8,9,10],
  [11,12,13,14,15,16,17,18,19,20],
  [21,22,23,24,25,26,27,28,29,30]])
print(A)
# factorize
U, s, V = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
V = V[:n_elements, :]
# reconstruct
B = U.dot(Sigma.dot(V))
print(B)
# transform
T = U.dot(Sigma)
print(T)
T = A.dot(V.T)
print(T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [59]:
# svd data reduction in scikit-learn
from numpy import array
from sklearn.decomposition import TruncatedSVD
# define matrix
A = array([
  [1,2,3,4,5,6,7,8,9,10],
  [11,12,13,14,15,16,17,18,19,20],
  [21,22,23,24,25,26,27,28,29,30]])
print(A)
# create transform
svd = TruncatedSVD(n_components=2)
# fit transform
svd.fit(A)
# apply transform
result = svd.transform(A)
print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]


# Multivariate Statistics

## Expected Value and Mean

In [60]:
# vector mean
from numpy import array
from numpy import mean
# define vector
v = array([1,2,3,4,5,6])
print(v)
# calculate mean
result = mean(v)
print(result)

[1 2 3 4 5 6]
3.5


In [61]:
# matrix means
from numpy import array
from numpy import mean
# define matrix
M = array([
  [1,2,3,4,5,6],
  [1,2,3,4,5,6]])
print(M)
# column means
col_mean = mean(M, axis=0)
print(col_mean)
# row means
row_mean = mean(M, axis=1)
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[1. 2. 3. 4. 5. 6.]
[3.5 3.5]


## Variance and Standard Deviation

In [62]:
# matrix means
from numpy import array
from numpy import mean
# define matrix
M = array([
  [1,2,3,4,5,6],
  [1,2,3,4,5,6]])
print(M)
# column means
col_mean = mean(M, axis=0)
print(col_mean)
# row means
row_mean = mean(M, axis=1)
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[1. 2. 3. 4. 5. 6.]
[3.5 3.5]


In [63]:
# vector variance
from numpy import array
from numpy import var
# define vector
v = array([1,2,3,4,5,6])
print(v)
# calculate variance
result = var(v, ddof=1)
print(result)

[1 2 3 4 5 6]
3.5


In [64]:
# matrix variances
from numpy import array
from numpy import var
# define matrix
M = array([
  [1,2,3,4,5,6],
  [1,2,3,4,5,6]])
print(M)
# column variances
col_var = var(M, ddof=1, axis=0)
print(col_var)
# row variances
row_var = var(M, ddof=1, axis=1)
print(row_var)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[3.5 3.5]


In [65]:
# matrix standard deviation
from numpy import array
from numpy import std
# define matrix
M = array([
  [1,2,3,4,5,6],
  [1,2,3,4,5,6]])
print(M)
# column standard deviations
col_std = std(M, ddof=1, axis=0)
print(col_std)
# row standard deviations
row_std = std(M, ddof=1, axis=1)
print(row_std)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[1.87082869 1.87082869]


## Covariance and Correlation

In [66]:
# vector covariance
from numpy import array
from numpy import cov
# define first vector
x = array([1,2,3,4,5,6,7,8,9])
print(x)
# define second covariance
y = array([9,8,7,6,5,4,3,2,1])
print(y)
# calculate covariance
Sigma = cov(x,y)[0,1]
print(Sigma)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
-7.5


In [67]:
# vector correlation
from numpy import array
from numpy import corrcoef
# define first vector
x = array([1,2,3,4,5,6,7,8,9])
print(x)
# define second vector
y = array([9,8,7,6,5,4,3,2,1])
print(y)
# calculate correlation
corr = corrcoef(x,y)[0,1]
print(corr)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
-1.0


In [68]:
# vector correlation
from numpy import array
from numpy import corrcoef
# define first vector
x = array([1,2,3,4,5,6,7,8,9])
print(x)
# define second vector
y = array([1,4,1,4,5,6,7,8,9])
print(y)
# calculate correlation
corr = corrcoef(x,y)[0,1]
print(corr)

[1 2 3 4 5 6 7 8 9]
[1 4 1 4 5 6 7 8 9]
0.935970975333459


In [69]:
# covariance matrix
from numpy import array
from numpy import cov
# define matrix of observations
X = array([
  [1, 5, 8],
  [3, 5, 11],
  [2, 4, 9],
  [3, 6, 10],
  [1, 5, 10]])
print(X)
# calculate covariance matrix
Sigma = cov(X.T)
print(Sigma)

[[ 1  5  8]
 [ 3  5 11]
 [ 2  4  9]
 [ 3  6 10]
 [ 1  5 10]]
[[1.   0.25 0.75]
 [0.25 0.5  0.25]
 [0.75 0.25 1.3 ]]


In [70]:
# covariance matrix
from numpy import array
from numpy import cov
# define matrix of observations
X = array([
  [1, 1, 1],
  [3, 5, 11],
  [2, 4, 9],
  [3, 6, 10],
  [1, 5, 10]])
print(X)
# calculate covariance matrix
Sigma = cov(X.T)
print(Sigma)

[[ 1  1  1]
 [ 3  5 11]
 [ 2  4  9]
 [ 3  6 10]
 [ 1  5 10]]
[[ 1.    1.25  2.5 ]
 [ 1.25  3.7   7.45]
 [ 2.5   7.45 16.7 ]]
